// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9997' | (string & {});
};

export type OkStatus = 'ok';

export type ErrorStatus = 'error';

export type PathSourceType = 'hlsSource' | 'redirect' | 'rpiCameraSource' | 'rtmpConn' | 'rtmpsConn' | 'rtmpSource' | 'rtspSession' | 'rtspSource' | 'rtspsSession' | 'srtConn' | 'srtSource' | 'mpegtsSource' | 'rtpSource' | 'webRTCSession' | 'webRTCSource';

export type PathReaderType = 'hlsMuxer' | 'rpiCameraSecondary' | 'rtmpConn' | 'rtmpsConn' | 'rtspConn' | 'rtspSession' | 'rtspsConn' | 'rtspsSession' | 'srtConn' | 'webRTCSession';

export type PathTrackCodec = 'AV1' | 'VP9' | 'VP8' | 'H265' | 'H264' | 'MPEG-4 Video' | 'MPEG-1 Video' | 'MJPEG' | 'Opus' | 'Vorbis' | 'MPEG-4 Audio' | 'MPEG-4 Audio LATM' | 'MPEG-1 Audio' | 'AC3' | 'Speex' | 'G726' | 'G722' | 'G711' | 'LPCM' | 'MPEG-TS' | 'KLV' | 'Generic';

export type AlwaysAvailableTrackCodec = 'AV1' | 'VP9' | 'H265' | 'H264' | 'MPEG4Audio' | 'Opus' | 'G711' | 'LPCM';

export type AuthAction = 'publish' | 'read' | 'playback' | 'api' | 'metrics' | 'pprof';

export type AuthMethod = 'internal' | 'http' | 'jwt';

export type Encryption = 'no' | 'optional' | 'strict';

export type HlsVariant = 'mpegts' | 'fmp4' | 'lowLatency';

export type LogDestination = 'stdout' | 'file' | 'syslog';

export type LogLevel = 'error' | 'warn' | 'info' | 'debug';

export type RecordFormat = 'fmp4' | 'mpegts';

export type RtspAuthMethod = 'basic' | 'digest';

export type RtspRangeType = '' | 'clock' | 'npt' | 'smpte';

export type RtspTransport = 'udp' | 'multicast' | 'tcp' | 'automatic';

export type RtmpConnState = 'idle' | 'read' | 'publish';

export type RtspSessionState = 'idle' | 'read' | 'publish';

export type SrtConnState = 'idle' | 'read' | 'publish';

export type WebRtcSessionState = 'read' | 'publish';

export type Ok = {
    status?: OkStatus;
};

export type Error = {
    status?: ErrorStatus;
    error?: string;
};

export type Info = {
    version?: string;
    started?: string;
};

export type AuthInternalUser = {
    user?: string;
    pass?: string;
    ips?: Array<string>;
    permissions?: Array<AuthInternalUserPermission>;
};

export type AuthInternalUserPermission = {
    action?: AuthAction;
    path?: string;
};

export type GlobalConf = {
    logLevel?: LogLevel;
    logDestinations?: Array<LogDestination>;
    logStructured?: boolean;
    logFile?: string;
    sysLogPrefix?: string;
    dumpPackets?: boolean;
    readTimeout?: string;
    writeTimeout?: string;
    /**
     * @deprecated
     */
    readBufferCount?: number | null;
    writeQueueSize?: number;
    udpMaxPayloadSize?: number;
    udpReadBufferSize?: number;
    runOnConnect?: string;
    runOnConnectRestart?: boolean;
    runOnDisconnect?: string;
    authMethod?: AuthMethod;
    authInternalUsers?: Array<AuthInternalUser>;
    authHTTPAddress?: string;
    /**
     * @deprecated
     */
    externalAuthenticationURL?: string | null;
    authHTTPFingerprint?: string;
    authHTTPExclude?: Array<AuthInternalUserPermission>;
    authJWTJWKS?: string;
    authJWTJWKSFingerprint?: string;
    authJWTClaimKey?: string;
    authJWTIssuer?: string;
    authJWTAudience?: string;
    authJWTExclude?: Array<AuthInternalUserPermission>;
    authJWTInHTTPQuery?: boolean;
    api?: boolean;
    apiAddress?: string;
    apiEncryption?: boolean;
    apiServerKey?: string;
    apiServerCert?: string;
    /**
     * @deprecated
     */
    apiAllowOrigin?: string | null;
    apiAllowOrigins?: Array<string>;
    apiTrustedProxies?: Array<string>;
    metrics?: boolean;
    metricsAddress?: string;
    metricsEncryption?: boolean;
    metricsServerKey?: string;
    metricsServerCert?: string;
    /**
     * @deprecated
     */
    metricsAllowOrigin?: string | null;
    metricsAllowOrigins?: Array<string>;
    metricsTrustedProxies?: Array<string>;
    pprof?: boolean;
    pprofAddress?: string;
    pprofEncryption?: boolean;
    pprofServerKey?: string;
    pprofServerCert?: string;
    /**
     * @deprecated
     */
    pprofAllowOrigin?: string | null;
    pprofAllowOrigins?: Array<string>;
    pprofTrustedProxies?: Array<string>;
    playback?: boolean;
    playbackAddress?: string;
    playbackEncryption?: boolean;
    playbackServerKey?: string;
    playbackServerCert?: string;
    /**
     * @deprecated
     */
    playbackAllowOrigin?: string | null;
    playbackAllowOrigins?: Array<string>;
    playbackTrustedProxies?: Array<string>;
    rtsp?: boolean;
    /**
     * @deprecated
     */
    rtspDisable?: boolean | null;
    /**
     * @deprecated
     */
    protocols?: Array<'udp' | 'multicast' | 'tcp'> | null;
    rtspTransports?: Array<'udp' | 'multicast' | 'tcp'>;
    /**
     * @deprecated
     */
    encryption?: Encryption | null;
    rtspEncryption?: Encryption;
    rtspAddress?: string;
    rtspsAddress?: string;
    rtpAddress?: string;
    rtcpAddress?: string;
    multicastIPRange?: string;
    multicastRTPPort?: number;
    multicastRTCPPort?: number;
    srtpAddress?: string;
    srtcpAddress?: string;
    multicastSRTPPort?: number;
    multicastSRTCPPort?: number;
    rtspServerKey?: string;
    rtspServerCert?: string;
    /**
     * @deprecated
     */
    authMethods?: Array<RtspAuthMethod> | null;
    rtspAuthMethods?: Array<RtspAuthMethod>;
    /**
     * @deprecated
     */
    rtspUDPReadBufferSize?: number | null;
    rtmp?: boolean;
    /**
     * @deprecated
     */
    rtmpDisable?: boolean | null;
    rtmpEncryption?: Encryption;
    rtmpAddress?: string;
    rtmpsAddress?: string;
    rtmpServerKey?: string;
    rtmpServerCert?: string;
    hls?: boolean;
    /**
     * @deprecated
     */
    hlsDisable?: boolean | null;
    hlsAddress?: string;
    hlsEncryption?: boolean;
    hlsServerKey?: string;
    hlsServerCert?: string;
    /**
     * @deprecated
     */
    hlsAllowOrigin?: string | null;
    hlsAllowOrigins?: Array<string>;
    hlsTrustedProxies?: Array<string>;
    hlsAlwaysRemux?: boolean;
    hlsVariant?: HlsVariant;
    hlsSegmentCount?: number;
    hlsSegmentDuration?: string;
    hlsPartDuration?: string;
    hlsSegmentMaxSize?: string;
    hlsDirectory?: string;
    hlsMuxerCloseAfter?: string;
    webrtc?: boolean;
    /**
     * @deprecated
     */
    webrtcDisable?: boolean | null;
    webrtcAddress?: string;
    webrtcEncryption?: boolean;
    webrtcServerKey?: string;
    webrtcServerCert?: string;
    /**
     * @deprecated
     */
    webrtcAllowOrigin?: string | null;
    webrtcAllowOrigins?: Array<string>;
    webrtcTrustedProxies?: Array<string>;
    webrtcLocalUDPAddress?: string;
    webrtcLocalTCPAddress?: string;
    webrtcIPsFromInterfaces?: boolean;
    webrtcIPsFromInterfacesList?: Array<string>;
    webrtcAdditionalHosts?: Array<string>;
    webrtcICEServers2?: Array<WebRtciceServer>;
    webrtcSTUNGatherTimeout?: string;
    webrtcHandshakeTimeout?: string;
    webrtcTrackGatherTimeout?: string;
    /**
     * @deprecated
     */
    webrtcICEUDPMuxAddress?: string | null;
    /**
     * @deprecated
     */
    webrtcICETCPMuxAddress?: string | null;
    /**
     * @deprecated
     */
    webrtcICEHostNAT1To1IPs?: Array<string> | null;
    /**
     * @deprecated
     */
    webrtcICEServers?: Array<string> | null;
    srt?: boolean;
    srtAddress?: string;
    /**
     * @deprecated
     */
    record?: boolean | null;
    /**
     * @deprecated
     */
    recordPath?: string | null;
    /**
     * @deprecated
     */
    recordFormat?: RecordFormat | null;
    /**
     * @deprecated
     */
    recordPartDuration?: string | null;
    /**
     * @deprecated
     */
    recordSegmentDuration?: string | null;
    /**
     * @deprecated
     */
    recordDeleteAfter?: string | null;
};

export type PathConf = {
    name?: string;
    source?: string;
    sourceFingerprint?: string;
    sourceOnDemand?: boolean;
    sourceOnDemandStartTimeout?: string;
    sourceOnDemandCloseAfter?: string;
    maxReaders?: number;
    srtReadPassphrase?: string;
    /**
     * @deprecated
     */
    fallback?: string | null;
    useAbsoluteTimestamp?: boolean;
    alwaysAvailable?: boolean;
    alwaysAvailableTracks?: Array<AlwaysAvailableTrack>;
    alwaysAvailableFile?: string;
    record?: boolean;
    /**
     * @deprecated
     */
    playback?: boolean | null;
    recordPath?: string;
    recordFormat?: RecordFormat;
    recordPartDuration?: string;
    recordMaxPartSize?: string;
    recordSegmentDuration?: string;
    recordDeleteAfter?: string;
    /**
     * @deprecated
     */
    publishUser?: string | null;
    /**
     * @deprecated
     */
    publishPass?: string | null;
    /**
     * @deprecated
     */
    publishIPs?: Array<string> | null;
    /**
     * @deprecated
     */
    readUser?: string | null;
    /**
     * @deprecated
     */
    readPass?: string | null;
    /**
     * @deprecated
     */
    readIPs?: Array<string> | null;
    overridePublisher?: boolean;
    /**
     * @deprecated
     */
    disablePublisherOverride?: boolean | null;
    srtPublishPassphrase?: string;
    rtspDemuxMpegts?: boolean;
    rtspTransport?: RtspTransport;
    rtspAnyPort?: boolean;
    /**
     * @deprecated
     */
    sourceProtocol?: RtspTransport | null;
    /**
     * @deprecated
     */
    sourceAnyPortEnable?: boolean | null;
    rtspRangeType?: RtspRangeType;
    rtspRangeStart?: string;
    /**
     * @deprecated
     */
    rtspUDPReadBufferSize?: number | null;
    rtspUDPSourcePortRange?: [
        number,
        number
    ];
    /**
     * @deprecated
     */
    mpegtsUDPReadBufferSize?: number | null;
    rtpSDP?: string;
    /**
     * @deprecated
     */
    rtpUDPReadBufferSize?: number | null;
    whepBearerToken?: string;
    whepSTUNGatherTimeout?: string;
    whepHandshakeTimeout?: string;
    whepTrackGatherTimeout?: string;
    sourceRedirect?: string;
    rpiCameraCamID?: number;
    rpiCameraSecondary?: boolean;
    rpiCameraWidth?: number;
    rpiCameraHeight?: number;
    rpiCameraHFlip?: boolean;
    rpiCameraVFlip?: boolean;
    rpiCameraBrightness?: number;
    rpiCameraContrast?: number;
    rpiCameraSaturation?: number;
    rpiCameraSharpness?: number;
    rpiCameraExposure?: string;
    rpiCameraAWB?: string;
    rpiCameraAWBGains?: [
        number,
        number
    ];
    rpiCameraDenoise?: string;
    rpiCameraShutter?: number;
    rpiCameraMetering?: string;
    rpiCameraGain?: number;
    rpiCameraEV?: number;
    rpiCameraROI?: string;
    rpiCameraHDR?: boolean;
    rpiCameraTuningFile?: string;
    rpiCameraMode?: string;
    rpiCameraFPS?: number;
    rpiCameraAfMode?: string;
    rpiCameraAfRange?: string;
    rpiCameraAfSpeed?: string;
    rpiCameraLensPosition?: number;
    rpiCameraAfWindow?: string;
    rpiCameraFlickerPeriod?: number;
    rpiCameraTextOverlayEnable?: boolean;
    rpiCameraTextOverlay?: string;
    rpiCameraCodec?: string;
    rpiCameraIDRPeriod?: number;
    rpiCameraBitrate?: number;
    /**
     * @deprecated
     */
    rpiCameraProfile?: string | null;
    /**
     * @deprecated
     */
    rpiCameraLevel?: string | null;
    rpiCameraHardwareH264Profile?: string;
    rpiCameraHardwareH264Level?: string;
    rpiCameraSoftwareH264Profile?: string;
    rpiCameraSoftwareH264Level?: string;
    /**
     * @deprecated
     */
    rpiCameraJPEGQuality?: number | null;
    rpiCameraMJPEGQuality?: number;
    runOnInit?: string;
    runOnInitRestart?: boolean;
    runOnDemand?: string;
    runOnDemandRestart?: boolean;
    runOnDemandStartTimeout?: string;
    runOnDemandCloseAfter?: string;
    runOnUnDemand?: string;
    runOnReady?: string;
    runOnReadyRestart?: boolean;
    runOnNotReady?: string;
    runOnRead?: string;
    runOnReadRestart?: boolean;
    runOnUnread?: string;
    runOnRecordSegmentCreate?: string;
    runOnRecordSegmentComplete?: string;
};

export type PathConfList = {
    pageCount?: number;
    itemCount?: number;
    items?: Array<PathConf>;
};

export type Path = {
    name?: string;
    confName?: string;
    source?: PathSource | null;
    /**
     * @deprecated
     */
    ready?: boolean;
    /**
     * @deprecated
     */
    readyTime?: string | null;
    available?: boolean;
    availableTime?: string | null;
    online?: boolean;
    onlineTime?: string | null;
    /**
     * @deprecated
     */
    tracks?: Array<PathTrackCodec>;
    tracks2?: Array<PathTrack>;
    inboundBytes?: number;
    outboundBytes?: number;
    inboundFramesInError?: number;
    /**
     * @deprecated
     */
    bytesReceived?: number;
    /**
     * @deprecated
     */
    bytesSent?: number;
    readers?: Array<PathReader>;
};

export type PathList = {
    pageCount?: number;
    itemCount?: number;
    items?: Array<Path>;
};

export type PathSource = {
    type?: PathSourceType;
    id?: string;
};

export type PathReader = {
    type?: PathReaderType;
    id?: string;
};

export type PathTrack = {
    codec?: PathTrackCodec;
    codecProps?: PathTrackCodecProps | null;
};

export type PathTrackCodecProps = PathTrackCodecPropsAv1 | PathTrackCodecPropsVp9 | PathTrackCodecPropsH265 | PathTrackCodecPropsH264 | PathTrackCodecPropsOpus | PathTrackCodecPropsMpeg4Audio | PathTrackCodecPropsAc3 | PathTrackCodecPropsG711 | PathTrackCodecPropsLpcm;

export type PathTrackCodecPropsAv1 = {
    width?: number;
    height?: number;
    profile?: number;
    level?: number;
    tier?: number;
};

export type PathTrackCodecPropsVp9 = {
    profile?: number;
};

export type PathTrackCodecPropsH265 = {
    width?: number;
    height?: number;
    profile?: string;
    level?: string;
};

export type PathTrackCodecPropsH264 = {
    width?: number;
    height?: number;
    profile?: string;
    level?: string;
};

export type PathTrackCodecPropsOpus = {
    channelCount?: number;
};

export type PathTrackCodecPropsMpeg4Audio = {
    sampleRate?: number;
    channelCount?: number;
};

export type PathTrackCodecPropsAc3 = {
    sampleRate?: number;
    channelCount?: number;
};

export type PathTrackCodecPropsG711 = {
    muLaw?: boolean;
    sampleRate?: number;
    channelCount?: number;
};

export type PathTrackCodecPropsLpcm = {
    bitDepth?: number;
    sampleRate?: number;
    channelCount?: number;
};

export type HlsMuxer = {
    path?: string;
    created?: string;
    lastRequest?: string;
    outboundBytes?: number;
    outboundFramesDiscarded?: number;
    /**
     * @deprecated
     */
    bytesSent?: number;
};

export type HlsMuxerList = {
    pageCount?: number;
    itemCount?: number;
    items?: Array<HlsMuxer>;
};

export type Recording = {
    name?: string;
    segments?: Array<RecordingSegment>;
};

export type RecordingList = {
    pageCount?: number;
    itemCount?: number;
    items?: Array<Recording>;
};

export type RecordingSegment = {
    start?: string;
};

export type RtmpConn = {
    id?: string;
    created?: string;
    remoteAddr?: string;
    state?: RtmpConnState;
    path?: string;
    query?: string;
    user?: string;
    inboundBytes?: number;
    outboundBytes?: number;
    outboundFramesDiscarded?: number;
    /**
     * @deprecated
     */
    bytesReceived?: number;
    /**
     * @deprecated
     */
    bytesSent?: number;
};

export type RtmpConnList = {
    pageCount?: number;
    itemCount?: number;
    items?: Array<RtmpConn>;
};

export type RtspConn = {
    id?: string;
    created?: string;
    remoteAddr?: string;
    session?: string | null;
    tunnel?: string;
    inboundBytes?: number;
    outboundBytes?: number;
    /**
     * @deprecated
     */
    bytesReceived?: number;
    /**
     * @deprecated
     */
    bytesSent?: number;
};

export type RtspConnList = {
    pageCount?: number;
    itemCount?: number;
    items?: Array<RtspConn>;
};

export type RtspSession = {
    id?: string;
    created?: string;
    remoteAddr?: string;
    state?: RtspSessionState;
    path?: string;
    query?: string;
    user?: string;
    transport?: string | null;
    profile?: string | null;
    conns?: Array<string>;
    inboundBytes?: number;
    inboundRTPPackets?: number;
    inboundRTPPacketsLost?: number;
    inboundRTPPacketsInError?: number;
    inboundRTPPacketsJitter?: number;
    inboundRTCPPackets?: number;
    inboundRTCPPacketsInError?: number;
    outboundBytes?: number;
    outboundRTPPackets?: number;
    outboundRTPPacketsReportedLost?: number;
    outboundRTPPacketsDiscarded?: number;
    outboundRTCPPackets?: number;
    /**
     * @deprecated
     */
    bytesReceived?: number;
    /**
     * @deprecated
     */
    bytesSent?: number;
    /**
     * @deprecated
     */
    rtpPacketsReceived?: number;
    /**
     * @deprecated
     */
    rtpPacketsSent?: number;
    /**
     * @deprecated
     */
    rtpPacketsLost?: number;
    /**
     * @deprecated
     */
    rtpPacketsInError?: number;
    /**
     * @deprecated
     */
    rtpPacketsJitter?: number;
    /**
     * @deprecated
     */
    rtcpPacketsReceived?: number;
    /**
     * @deprecated
     */
    rtcpPacketsSent?: number;
    /**
     * @deprecated
     */
    rtcpPacketsInError?: number;
};

export type RtspSessionList = {
    pageCount?: number;
    itemCount?: number;
    items?: Array<RtspSession>;
};

export type SrtConn = {
    id?: string;
    created?: string;
    remoteAddr?: string;
    state?: SrtConnState;
    path?: string;
    query?: string;
    user?: string;
    /**
     * The total number of sent DATA packets, including retransmitted packets
     */
    packetsSent?: number;
    /**
     * The total number of received DATA packets, including retransmitted packets
     */
    packetsReceived?: number;
    packetsReceivedBelated?: number;
    /**
     * The total number of unique DATA packets sent by the SRT sender
     */
    packetsSentUnique?: number;
    /**
     * The total number of unique original, retransmitted or recovered by the packet filter DATA packets received in time, decrypted without errors and, as a result, scheduled for delivery to the upstream application by the SRT receiver.
     */
    packetsReceivedUnique?: number;
    /**
     * The total number of data packets considered or reported as lost at the sender side. Does not correspond to the packets detected as lost at the receiver side.
     */
    packetsSendLoss?: number;
    /**
     * The total number of SRT DATA packets detected as presently missing (either reordered or lost) at the receiver side
     */
    packetsReceivedLoss?: number;
    /**
     * The total number of retransmitted packets sent by the SRT sender
     */
    packetsRetrans?: number;
    /**
     * The total number of retransmitted packets registered at the receiver side
     */
    packetsReceivedRetrans?: number;
    /**
     * The total number of sent ACK (Acknowledgement) control packets
     */
    packetsSentACK?: number;
    /**
     * The total number of received ACK (Acknowledgement) control packets
     */
    packetsReceivedACK?: number;
    /**
     * The total number of sent NAK (Negative Acknowledgement) control packets
     */
    packetsSentNAK?: number;
    /**
     * The total number of received NAK (Negative Acknowledgement) control packets
     */
    packetsReceivedNAK?: number;
    /**
     * The total number of sent KM (Key Material) control packets
     */
    packetsSentKM?: number;
    /**
     * The total number of received KM (Key Material) control packets
     */
    packetsReceivedKM?: number;
    /**
     * The total accumulated time in microseconds, during which the SRT sender has some data to transmit, including packets that have been sent, but not yet acknowledged
     */
    usSndDuration?: number;
    /**
     * The total number of dropped by the SRT sender DATA packets that have no chance to be delivered in time
     */
    packetsSendDrop?: number;
    /**
     * The total number of dropped by the SRT receiver and, as a result, not delivered to the upstream application DATA packets
     */
    packetsReceivedDrop?: number;
    /**
     * The total number of packets that failed to be decrypted at the receiver side
     */
    packetsReceivedUndecrypt?: number;
    /**
     * Same as packetsSent, but expressed in bytes, including payload and all the headers (IP, TCP, SRT)
     */
    bytesSent?: number;
    /**
     * Same as packetsReceived, but expressed in bytes, including payload and all the headers (IP, TCP, SRT)
     */
    bytesReceived?: number;
    bytesReceivedBelated?: number;
    /**
     * Same as packetsSentUnique, but expressed in bytes, including payload and all the headers (IP, TCP, SRT)
     */
    bytesSentUnique?: number;
    /**
     * Same as packetsReceivedUnique, but expressed in bytes, including payload and all the headers (IP, TCP, SRT)
     */
    bytesReceivedUnique?: number;
    /**
     * Same as packetsReceivedLoss, but expressed in bytes, including payload and all the headers (IP, TCP, SRT), bytes for the presently missing (either reordered or lost) packets' payloads are estimated based on the average packet size
     */
    bytesReceivedLoss?: number;
    /**
     * Same as packetsRetrans, but expressed in bytes, including payload and all the headers (IP, TCP, SRT)
     */
    bytesRetrans?: number;
    /**
     * Same as packetsReceivedRetrans, but expressed in bytes, including payload and all the headers (IP, TCP, SRT)
     */
    bytesReceivedRetrans?: number;
    /**
     * Same as packetsSendDrop, but expressed in bytes, including payload and all the headers (IP, TCP, SRT)
     */
    bytesSendDrop?: number;
    /**
     * Same as packetsReceivedDrop, but expressed in bytes, including payload and all the headers (IP, TCP, SRT)
     */
    bytesReceivedDrop?: number;
    /**
     * Same as packetsReceivedUndecrypt, but expressed in bytes, including payload and all the headers (IP, TCP, SRT)
     */
    bytesReceivedUndecrypt?: number;
    /**
     * Current minimum time interval between which consecutive packets are sent, in microseconds
     */
    usPacketsSendPeriod?: number;
    /**
     * The maximum number of packets that can be "in flight"
     */
    packetsFlowWindow?: number;
    /**
     * The number of packets in flight
     */
    packetsFlightSize?: number;
    /**
     * Smoothed round-trip time (SRTT), an exponentially-weighted moving average (EWMA) of an endpoint's RTT samples, in milliseconds
     */
    msRTT?: number;
    /**
     * Current transmission bandwidth, in Mbps
     */
    mbpsSendRate?: number;
    /**
     * Current receiving bandwidth, in Mbps
     */
    mbpsReceiveRate?: number;
    /**
     * Estimated capacity of the network link, in Mbps
     */
    mbpsLinkCapacity?: number;
    /**
     * The available space in the sender's buffer, in bytes
     */
    bytesAvailSendBuf?: number;
    /**
     * The available space in the receiver's buffer, in bytes
     */
    bytesAvailReceiveBuf?: number;
    /**
     * Transmission bandwidth limit, in Mbps
     */
    mbpsMaxBW?: number;
    /**
     * Maximum Segment Size (MSS), in bytes
     */
    byteMSS?: number;
    /**
     * The number of packets in the sender's buffer that are already scheduled for sending or even possibly sent, but not yet acknowledged
     */
    packetsSendBuf?: number;
    /**
     * Instantaneous (current) value of packetsSndBuf, but expressed in bytes, including payload and all headers (IP, TCP, SRT)
     */
    bytesSendBuf?: number;
    /**
     * The timespan (msec) of packets in the sender's buffer (unacknowledged packets)
     */
    msSendBuf?: number;
    /**
     * Timestamp-based Packet Delivery Delay value of the peer
     */
    msSendTsbPdDelay?: number;
    /**
     * The number of acknowledged packets in receiver's buffer
     */
    packetsReceiveBuf?: number;
    /**
     * Instantaneous (current) value of packetsRcvBuf, expressed in bytes, including payload and all headers (IP, TCP, SRT)
     */
    bytesReceiveBuf?: number;
    /**
     * The timespan (msec) of acknowledged packets in the receiver's buffer
     */
    msReceiveBuf?: number;
    /**
     * Timestamp-based Packet Delivery Delay value set on the socket via SRTO_RCVLATENCY or SRTO_LATENCY
     */
    msReceiveTsbPdDelay?: number;
    /**
     * Instant value of the packet reorder tolerance
     */
    packetsReorderTolerance?: number;
    /**
     * Accumulated difference between the current time and the time-to-play of a packet that is received late
     */
    packetsReceivedAvgBelatedTime?: number;
    /**
     * Percentage of resent data vs. sent data
     */
    packetsSendLossRate?: number;
    /**
     * Percentage of retransmitted data vs. received data
     */
    packetsReceivedLossRate?: number;
    outboundFramesDiscarded?: number;
};

export type SrtConnList = {
    pageCount?: number;
    itemCount?: number;
    items?: Array<SrtConn>;
};

export type AlwaysAvailableTrack = {
    codec?: AlwaysAvailableTrackCodec;
    sampleRate?: number;
    channelCount?: number;
    muLaw?: boolean;
};

export type WebRtciceServer = {
    url?: string;
    username?: string;
    password?: string;
    clientOnly?: boolean;
};

export type WebRtcSession = {
    id?: string;
    created?: string;
    remoteAddr?: string;
    peerConnectionEstablished?: boolean;
    localCandidate?: string;
    remoteCandidate?: string;
    state?: WebRtcSessionState;
    path?: string;
    query?: string;
    user?: string;
    inboundBytes?: number;
    inboundRTPPackets?: number;
    inboundRTPPacketsLost?: number;
    inboundRTPPacketsJitter?: number;
    inboundRTCPPackets?: number;
    outboundBytes?: number;
    outboundRTPPackets?: number;
    outboundRTCPPackets?: number;
    outboundFramesDiscarded?: number;
    /**
     * @deprecated
     */
    bytesReceived?: number;
    /**
     * @deprecated
     */
    bytesSent?: number;
    /**
     * @deprecated
     */
    rtpPacketsReceived?: number;
    /**
     * @deprecated
     */
    rtpPacketsSent?: number;
    /**
     * @deprecated
     */
    rtpPacketsLost?: number;
    /**
     * @deprecated
     */
    rtpPacketsJitter?: number;
    /**
     * @deprecated
     */
    rtcpPacketsReceived?: number;
    /**
     * @deprecated
     */
    rtcpPacketsSent?: number;
};

export type WebRtcSessionList = {
    pageCount?: number;
    itemCount?: number;
    items?: Array<WebRtcSession>;
};

export type InfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/info';
};

export type InfoErrors = {
    /**
     * server error.
     */
    500: Error;
};

export type InfoError = InfoErrors[keyof InfoErrors];

export type InfoResponses = {
    /**
     * the request was successful.
     */
    200: Info;
};

export type InfoResponse = InfoResponses[keyof InfoResponses];

export type AuthJwksRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/auth/jwks/refresh';
};

export type AuthJwksRefreshErrors = {
    /**
     * server error.
     */
    500: Error;
};

export type AuthJwksRefreshError = AuthJwksRefreshErrors[keyof AuthJwksRefreshErrors];

export type AuthJwksRefreshResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type AuthJwksRefreshResponse = AuthJwksRefreshResponses[keyof AuthJwksRefreshResponses];

export type ConfigGlobalGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/config/global/get';
};

export type ConfigGlobalGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigGlobalGetError = ConfigGlobalGetErrors[keyof ConfigGlobalGetErrors];

export type ConfigGlobalGetResponses = {
    /**
     * the request was successful.
     */
    200: GlobalConf;
};

export type ConfigGlobalGetResponse = ConfigGlobalGetResponses[keyof ConfigGlobalGetResponses];

export type ConfigGlobalSetData = {
    body: GlobalConf;
    path?: never;
    query?: never;
    url: '/v3/config/global/patch';
};

export type ConfigGlobalSetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigGlobalSetError = ConfigGlobalSetErrors[keyof ConfigGlobalSetErrors];

export type ConfigGlobalSetResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type ConfigGlobalSetResponse = ConfigGlobalSetResponses[keyof ConfigGlobalSetResponses];

export type ConfigPathDefaultsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/config/pathdefaults/get';
};

export type ConfigPathDefaultsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigPathDefaultsGetError = ConfigPathDefaultsGetErrors[keyof ConfigPathDefaultsGetErrors];

export type ConfigPathDefaultsGetResponses = {
    /**
     * the request was successful.
     */
    200: PathConf;
};

export type ConfigPathDefaultsGetResponse = ConfigPathDefaultsGetResponses[keyof ConfigPathDefaultsGetResponses];

export type ConfigPathDefaultsPatchData = {
    body: PathConf;
    path?: never;
    query?: never;
    url: '/v3/config/pathdefaults/patch';
};

export type ConfigPathDefaultsPatchErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigPathDefaultsPatchError = ConfigPathDefaultsPatchErrors[keyof ConfigPathDefaultsPatchErrors];

export type ConfigPathDefaultsPatchResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type ConfigPathDefaultsPatchResponse = ConfigPathDefaultsPatchResponses[keyof ConfigPathDefaultsPatchResponses];

export type ConfigPathsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/config/paths/list';
};

export type ConfigPathsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigPathsListError = ConfigPathsListErrors[keyof ConfigPathsListErrors];

export type ConfigPathsListResponses = {
    /**
     * the request was successful.
     */
    200: PathConfList;
};

export type ConfigPathsListResponse = ConfigPathsListResponses[keyof ConfigPathsListResponses];

export type ConfigPathsGetData = {
    body?: never;
    path: {
        /**
         * the name of the path.
         */
        name: string;
    };
    query?: never;
    url: '/v3/config/paths/get/{name}';
};

export type ConfigPathsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * path not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigPathsGetError = ConfigPathsGetErrors[keyof ConfigPathsGetErrors];

export type ConfigPathsGetResponses = {
    /**
     * the request was successful.
     */
    200: PathConf;
};

export type ConfigPathsGetResponse = ConfigPathsGetResponses[keyof ConfigPathsGetResponses];

export type ConfigPathsAddData = {
    body: PathConf;
    path: {
        /**
         * the name of the path.
         */
        name: string;
    };
    query?: never;
    url: '/v3/config/paths/add/{name}';
};

export type ConfigPathsAddErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigPathsAddError = ConfigPathsAddErrors[keyof ConfigPathsAddErrors];

export type ConfigPathsAddResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type ConfigPathsAddResponse = ConfigPathsAddResponses[keyof ConfigPathsAddResponses];

export type ConfigPathsPatchData = {
    body: PathConf;
    path: {
        /**
         * the name of the path.
         */
        name: string;
    };
    query?: never;
    url: '/v3/config/paths/patch/{name}';
};

export type ConfigPathsPatchErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * path not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigPathsPatchError = ConfigPathsPatchErrors[keyof ConfigPathsPatchErrors];

export type ConfigPathsPatchResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type ConfigPathsPatchResponse = ConfigPathsPatchResponses[keyof ConfigPathsPatchResponses];

export type ConfigPathsReplaceData = {
    body: PathConf;
    path: {
        /**
         * the name of the path.
         */
        name: string;
    };
    query?: never;
    url: '/v3/config/paths/replace/{name}';
};

export type ConfigPathsReplaceErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * path not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigPathsReplaceError = ConfigPathsReplaceErrors[keyof ConfigPathsReplaceErrors];

export type ConfigPathsReplaceResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type ConfigPathsReplaceResponse = ConfigPathsReplaceResponses[keyof ConfigPathsReplaceResponses];

export type ConfigPathsDeleteData = {
    body?: never;
    path: {
        /**
         * the name of the path.
         */
        name: string;
    };
    query?: never;
    url: '/v3/config/paths/delete/{name}';
};

export type ConfigPathsDeleteErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * path not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type ConfigPathsDeleteError = ConfigPathsDeleteErrors[keyof ConfigPathsDeleteErrors];

export type ConfigPathsDeleteResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type ConfigPathsDeleteResponse = ConfigPathsDeleteResponses[keyof ConfigPathsDeleteResponses];

export type HlsMuxersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/hlsmuxers/list';
};

export type HlsMuxersListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type HlsMuxersListError = HlsMuxersListErrors[keyof HlsMuxersListErrors];

export type HlsMuxersListResponses = {
    /**
     * the request was successful.
     */
    200: HlsMuxerList;
};

export type HlsMuxersListResponse = HlsMuxersListResponses[keyof HlsMuxersListResponses];

export type HlsMuxersGetData = {
    body?: never;
    path: {
        /**
         * name of the muxer.
         */
        name: string;
    };
    query?: never;
    url: '/v3/hlsmuxers/get/{name}';
};

export type HlsMuxersGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * muxer not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type HlsMuxersGetError = HlsMuxersGetErrors[keyof HlsMuxersGetErrors];

export type HlsMuxersGetResponses = {
    /**
     * the request was successful.
     */
    200: HlsMuxer;
};

export type HlsMuxersGetResponse = HlsMuxersGetResponses[keyof HlsMuxersGetResponses];

export type PathsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/paths/list';
};

export type PathsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type PathsListError = PathsListErrors[keyof PathsListErrors];

export type PathsListResponses = {
    /**
     * the request was successful.
     */
    200: PathList;
};

export type PathsListResponse = PathsListResponses[keyof PathsListResponses];

export type PathsGetData = {
    body?: never;
    path: {
        /**
         * name of the path.
         */
        name: string;
    };
    query?: never;
    url: '/v3/paths/get/{name}';
};

export type PathsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * path not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type PathsGetError = PathsGetErrors[keyof PathsGetErrors];

export type PathsGetResponses = {
    /**
     * the request was successful.
     */
    200: Path;
};

export type PathsGetResponse = PathsGetResponses[keyof PathsGetResponses];

export type RtspConnsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/rtspconns/list';
};

export type RtspConnsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspConnsListError = RtspConnsListErrors[keyof RtspConnsListErrors];

export type RtspConnsListResponses = {
    /**
     * the request was successful.
     */
    200: RtspConnList;
};

export type RtspConnsListResponse = RtspConnsListResponses[keyof RtspConnsListResponses];

export type RtspConnsGetData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtspconns/get/{id}';
};

export type RtspConnsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * connection not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspConnsGetError = RtspConnsGetErrors[keyof RtspConnsGetErrors];

export type RtspConnsGetResponses = {
    /**
     * the request was successful.
     */
    200: RtspConn;
};

export type RtspConnsGetResponse = RtspConnsGetResponses[keyof RtspConnsGetResponses];

export type RtspSessionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/rtspsessions/list';
};

export type RtspSessionsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspSessionsListError = RtspSessionsListErrors[keyof RtspSessionsListErrors];

export type RtspSessionsListResponses = {
    /**
     * the request was successful.
     */
    200: RtspSessionList;
};

export type RtspSessionsListResponse = RtspSessionsListResponses[keyof RtspSessionsListResponses];

export type RtspSessionsGetData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtspsessions/get/{id}';
};

export type RtspSessionsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * session not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspSessionsGetError = RtspSessionsGetErrors[keyof RtspSessionsGetErrors];

export type RtspSessionsGetResponses = {
    /**
     * the request was successful.
     */
    200: RtspSession;
};

export type RtspSessionsGetResponse = RtspSessionsGetResponses[keyof RtspSessionsGetResponses];

export type RtspSessionsKickData = {
    body?: never;
    path: {
        /**
         * ID of the session.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtspsessions/kick/{id}';
};

export type RtspSessionsKickErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * session not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspSessionsKickError = RtspSessionsKickErrors[keyof RtspSessionsKickErrors];

export type RtspSessionsKickResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type RtspSessionsKickResponse = RtspSessionsKickResponses[keyof RtspSessionsKickResponses];

export type RtspsConnsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/rtspsconns/list';
};

export type RtspsConnsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspsConnsListError = RtspsConnsListErrors[keyof RtspsConnsListErrors];

export type RtspsConnsListResponses = {
    /**
     * the request was successful.
     */
    200: RtspConnList;
};

export type RtspsConnsListResponse = RtspsConnsListResponses[keyof RtspsConnsListResponses];

export type RtspsConnsGetData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtspsconns/get/{id}';
};

export type RtspsConnsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * connection not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspsConnsGetError = RtspsConnsGetErrors[keyof RtspsConnsGetErrors];

export type RtspsConnsGetResponses = {
    /**
     * the request was successful.
     */
    200: RtspConn;
};

export type RtspsConnsGetResponse = RtspsConnsGetResponses[keyof RtspsConnsGetResponses];

export type RtspsSessionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/rtspssessions/list';
};

export type RtspsSessionsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspsSessionsListError = RtspsSessionsListErrors[keyof RtspsSessionsListErrors];

export type RtspsSessionsListResponses = {
    /**
     * the request was successful.
     */
    200: RtspSessionList;
};

export type RtspsSessionsListResponse = RtspsSessionsListResponses[keyof RtspsSessionsListResponses];

export type RtspsSessionsGetData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtspssessions/get/{id}';
};

export type RtspsSessionsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * session not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspsSessionsGetError = RtspsSessionsGetErrors[keyof RtspsSessionsGetErrors];

export type RtspsSessionsGetResponses = {
    /**
     * the request was successful.
     */
    200: RtspSession;
};

export type RtspsSessionsGetResponse = RtspsSessionsGetResponses[keyof RtspsSessionsGetResponses];

export type RtspsSessionsKickData = {
    body?: never;
    path: {
        /**
         * ID of the session.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtspssessions/kick/{id}';
};

export type RtspsSessionsKickErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * session not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtspsSessionsKickError = RtspsSessionsKickErrors[keyof RtspsSessionsKickErrors];

export type RtspsSessionsKickResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type RtspsSessionsKickResponse = RtspsSessionsKickResponses[keyof RtspsSessionsKickResponses];

export type RtmpConnsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/rtmpconns/list';
};

export type RtmpConnsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtmpConnsListError = RtmpConnsListErrors[keyof RtmpConnsListErrors];

export type RtmpConnsListResponses = {
    /**
     * the request was successful.
     */
    200: RtmpConnList;
};

export type RtmpConnsListResponse = RtmpConnsListResponses[keyof RtmpConnsListResponses];

export type RtmpConnectionsGetData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtmpconns/get/{id}';
};

export type RtmpConnectionsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * connection not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtmpConnectionsGetError = RtmpConnectionsGetErrors[keyof RtmpConnectionsGetErrors];

export type RtmpConnectionsGetResponses = {
    /**
     * the request was successful.
     */
    200: RtmpConn;
};

export type RtmpConnectionsGetResponse = RtmpConnectionsGetResponses[keyof RtmpConnectionsGetResponses];

export type RtmpConnsKickData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtmpconns/kick/{id}';
};

export type RtmpConnsKickErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * connection not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtmpConnsKickError = RtmpConnsKickErrors[keyof RtmpConnsKickErrors];

export type RtmpConnsKickResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type RtmpConnsKickResponse = RtmpConnsKickResponses[keyof RtmpConnsKickResponses];

export type RtmpsConnsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/rtmpsconns/list';
};

export type RtmpsConnsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtmpsConnsListError = RtmpsConnsListErrors[keyof RtmpsConnsListErrors];

export type RtmpsConnsListResponses = {
    /**
     * the request was successful.
     */
    200: RtmpConnList;
};

export type RtmpsConnsListResponse = RtmpsConnsListResponses[keyof RtmpsConnsListResponses];

export type RtmpsConnectionsGetData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtmpsconns/get/{id}';
};

export type RtmpsConnectionsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * connection not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtmpsConnectionsGetError = RtmpsConnectionsGetErrors[keyof RtmpsConnectionsGetErrors];

export type RtmpsConnectionsGetResponses = {
    /**
     * the request was successful.
     */
    200: RtmpConn;
};

export type RtmpsConnectionsGetResponse = RtmpsConnectionsGetResponses[keyof RtmpsConnectionsGetResponses];

export type RtmpsConnsKickData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/rtmpsconns/kick/{id}';
};

export type RtmpsConnsKickErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * connection not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RtmpsConnsKickError = RtmpsConnsKickErrors[keyof RtmpsConnsKickErrors];

export type RtmpsConnsKickResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type RtmpsConnsKickResponse = RtmpsConnsKickResponses[keyof RtmpsConnsKickResponses];

export type SrtConnsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/srtconns/list';
};

export type SrtConnsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type SrtConnsListError = SrtConnsListErrors[keyof SrtConnsListErrors];

export type SrtConnsListResponses = {
    /**
     * the request was successful.
     */
    200: SrtConnList;
};

export type SrtConnsListResponse = SrtConnsListResponses[keyof SrtConnsListResponses];

export type SrtConnsGetData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/srtconns/get/{id}';
};

export type SrtConnsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * connection not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type SrtConnsGetError = SrtConnsGetErrors[keyof SrtConnsGetErrors];

export type SrtConnsGetResponses = {
    /**
     * the request was successful.
     */
    200: SrtConn;
};

export type SrtConnsGetResponse = SrtConnsGetResponses[keyof SrtConnsGetResponses];

export type SrtConnsKickData = {
    body?: never;
    path: {
        /**
         * ID of the connection.
         */
        id: string;
    };
    query?: never;
    url: '/v3/srtconns/kick/{id}';
};

export type SrtConnsKickErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * connection not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type SrtConnsKickError = SrtConnsKickErrors[keyof SrtConnsKickErrors];

export type SrtConnsKickResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type SrtConnsKickResponse = SrtConnsKickResponses[keyof SrtConnsKickResponses];

export type WebrtcSessionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/webrtcsessions/list';
};

export type WebrtcSessionsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type WebrtcSessionsListError = WebrtcSessionsListErrors[keyof WebrtcSessionsListErrors];

export type WebrtcSessionsListResponses = {
    /**
     * the request was successful.
     */
    200: WebRtcSessionList;
};

export type WebrtcSessionsListResponse = WebrtcSessionsListResponses[keyof WebrtcSessionsListResponses];

export type WebrtcSessionsGetData = {
    body?: never;
    path: {
        /**
         * ID of the session.
         */
        id: string;
    };
    query?: never;
    url: '/v3/webrtcsessions/get/{id}';
};

export type WebrtcSessionsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * session not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type WebrtcSessionsGetError = WebrtcSessionsGetErrors[keyof WebrtcSessionsGetErrors];

export type WebrtcSessionsGetResponses = {
    /**
     * the request was successful.
     */
    200: WebRtcSession;
};

export type WebrtcSessionsGetResponse = WebrtcSessionsGetResponses[keyof WebrtcSessionsGetResponses];

export type WebrtcSessionsKickData = {
    body?: never;
    path: {
        /**
         * ID of the session.
         */
        id: string;
    };
    query?: never;
    url: '/v3/webrtcsessions/kick/{id}';
};

export type WebrtcSessionsKickErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * session not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type WebrtcSessionsKickError = WebrtcSessionsKickErrors[keyof WebrtcSessionsKickErrors];

export type WebrtcSessionsKickResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type WebrtcSessionsKickResponse = WebrtcSessionsKickResponses[keyof WebrtcSessionsKickResponses];

export type RecordingsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * page number.
         */
        page?: number;
        /**
         * items per page.
         */
        itemsPerPage?: number;
    };
    url: '/v3/recordings/list';
};

export type RecordingsListErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RecordingsListError = RecordingsListErrors[keyof RecordingsListErrors];

export type RecordingsListResponses = {
    /**
     * the request was successful.
     */
    200: RecordingList;
};

export type RecordingsListResponse = RecordingsListResponses[keyof RecordingsListResponses];

export type RecordingsGetData = {
    body?: never;
    path: {
        /**
         * name of the path.
         */
        name: string;
    };
    query?: never;
    url: '/v3/recordings/get/{name}';
};

export type RecordingsGetErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * path not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RecordingsGetError = RecordingsGetErrors[keyof RecordingsGetErrors];

export type RecordingsGetResponses = {
    /**
     * the request was successful.
     */
    200: Recording;
};

export type RecordingsGetResponse = RecordingsGetResponses[keyof RecordingsGetResponses];

export type RecordingsDeleteSegmentData = {
    body?: never;
    path?: never;
    query: {
        /**
         * path.
         */
        path: string;
        /**
         * starting date of the segment.
         */
        start: string;
    };
    url: '/v3/recordings/deletesegment';
};

export type RecordingsDeleteSegmentErrors = {
    /**
     * invalid request.
     */
    400: Error;
    /**
     * connection not found.
     */
    404: Error;
    /**
     * server error.
     */
    500: Error;
};

export type RecordingsDeleteSegmentError = RecordingsDeleteSegmentErrors[keyof RecordingsDeleteSegmentErrors];

export type RecordingsDeleteSegmentResponses = {
    /**
     * the request was successful.
     */
    200: Ok;
};

export type RecordingsDeleteSegmentResponse = RecordingsDeleteSegmentResponses[keyof RecordingsDeleteSegmentResponses];
