// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zOkStatus = z.enum(['ok']);

export const zErrorStatus = z.enum(['error']);

export const zPathSourceType = z.enum([
    'hlsSource',
    'redirect',
    'rpiCameraSource',
    'rtmpConn',
    'rtmpsConn',
    'rtmpSource',
    'rtspSession',
    'rtspSource',
    'rtspsSession',
    'srtConn',
    'srtSource',
    'mpegtsSource',
    'rtpSource',
    'webRTCSession',
    'webRTCSource'
]);

export const zPathReaderType = z.enum([
    'hlsMuxer',
    'rpiCameraSecondary',
    'rtmpConn',
    'rtmpsConn',
    'rtspConn',
    'rtspSession',
    'rtspsConn',
    'rtspsSession',
    'srtConn',
    'webRTCSession'
]);

export const zPathTrackCodec = z.enum([
    'AV1',
    'VP9',
    'VP8',
    'H265',
    'H264',
    'MPEG-4 Video',
    'MPEG-1 Video',
    'MJPEG',
    'Opus',
    'Vorbis',
    'MPEG-4 Audio',
    'MPEG-4 Audio LATM',
    'MPEG-1 Audio',
    'AC3',
    'Speex',
    'G726',
    'G722',
    'G711',
    'LPCM',
    'MPEG-TS',
    'KLV',
    'Generic'
]);

export const zAlwaysAvailableTrackCodec = z.enum([
    'AV1',
    'VP9',
    'H265',
    'H264',
    'MPEG4Audio',
    'Opus',
    'G711',
    'LPCM'
]);

export const zAuthAction = z.enum([
    'publish',
    'read',
    'playback',
    'api',
    'metrics',
    'pprof'
]);

export const zAuthMethod = z.enum([
    'internal',
    'http',
    'jwt'
]);

export const zEncryption = z.enum([
    'no',
    'optional',
    'strict'
]);

export const zHlsVariant = z.enum([
    'mpegts',
    'fmp4',
    'lowLatency'
]);

export const zLogDestination = z.enum([
    'stdout',
    'file',
    'syslog'
]);

export const zLogLevel = z.enum([
    'error',
    'warn',
    'info',
    'debug'
]);

export const zRecordFormat = z.enum(['fmp4', 'mpegts']);

export const zRtspAuthMethod = z.enum(['basic', 'digest']);

export const zRtspRangeType = z.enum([
    '',
    'clock',
    'npt',
    'smpte'
]);

export const zRtspTransport = z.enum([
    'udp',
    'multicast',
    'tcp',
    'automatic'
]);

export const zRtmpConnState = z.enum([
    'idle',
    'read',
    'publish'
]);

export const zRtspSessionState = z.enum([
    'idle',
    'read',
    'publish'
]);

export const zSrtConnState = z.enum([
    'idle',
    'read',
    'publish'
]);

export const zWebRtcSessionState = z.enum(['read', 'publish']);

export const zOk = z.object({
    status: zOkStatus.optional()
});

export const zError = z.object({
    status: zErrorStatus.optional(),
    error: z.string().optional()
});

export const zInfo = z.object({
    version: z.string().optional(),
    started: z.string().optional()
});

export const zAuthInternalUserPermission = z.object({
    action: zAuthAction.optional(),
    path: z.string().optional()
});

export const zAuthInternalUser = z.object({
    user: z.string().optional(),
    pass: z.string().optional(),
    ips: z.array(z.string()).optional(),
    permissions: z.array(zAuthInternalUserPermission).optional()
});

export const zPathSource = z.object({
    type: zPathSourceType.optional(),
    id: z.string().optional()
});

export const zPathReader = z.object({
    type: zPathReaderType.optional(),
    id: z.string().optional()
});

export const zPathTrackCodecPropsAv1 = z.object({
    width: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    height: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    profile: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    level: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    tier: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

export const zPathTrackCodecPropsVp9 = z.object({
    profile: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

export const zPathTrackCodecPropsH265 = z.object({
    width: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    height: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    profile: z.string().optional(),
    level: z.string().optional()
});

export const zPathTrackCodecPropsH264 = z.object({
    width: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    height: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    profile: z.string().optional(),
    level: z.string().optional()
});

export const zPathTrackCodecPropsOpus = z.object({
    channelCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

export const zPathTrackCodecPropsMpeg4Audio = z.object({
    sampleRate: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    channelCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

export const zPathTrackCodecPropsAc3 = z.object({
    sampleRate: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    channelCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

export const zPathTrackCodecPropsG711 = z.object({
    muLaw: z.boolean().optional(),
    sampleRate: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    channelCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

export const zPathTrackCodecPropsLpcm = z.object({
    bitDepth: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    sampleRate: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    channelCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

export const zPathTrackCodecProps = z.union([
    zPathTrackCodecPropsAv1,
    zPathTrackCodecPropsVp9,
    zPathTrackCodecPropsH265,
    zPathTrackCodecPropsH264,
    zPathTrackCodecPropsOpus,
    zPathTrackCodecPropsMpeg4Audio,
    zPathTrackCodecPropsAc3,
    zPathTrackCodecPropsG711,
    zPathTrackCodecPropsLpcm
]);

export const zPathTrack = z.object({
    codec: zPathTrackCodec.optional(),
    codecProps: zPathTrackCodecProps.nullish()
});

export const zPath = z.object({
    name: z.string().optional(),
    confName: z.string().optional(),
    source: zPathSource.nullish(),
    ready: z.boolean().optional(),
    readyTime: z.string().nullish(),
    available: z.boolean().optional(),
    availableTime: z.string().nullish(),
    online: z.boolean().optional(),
    onlineTime: z.string().nullish(),
    tracks: z.array(zPathTrackCodec).optional(),
    tracks2: z.array(zPathTrack).optional(),
    inboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    inboundFramesInError: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    readers: z.array(zPathReader).optional()
});

export const zPathList = z.object({
    pageCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    itemCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    items: z.array(zPath).optional()
});

export const zHlsMuxer = z.object({
    path: z.string().optional(),
    created: z.string().optional(),
    lastRequest: z.string().optional(),
    outboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundFramesDiscarded: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional()
});

export const zHlsMuxerList = z.object({
    pageCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    itemCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    items: z.array(zHlsMuxer).optional()
});

export const zRecordingSegment = z.object({
    start: z.string().optional()
});

export const zRecording = z.object({
    name: z.string().optional(),
    segments: z.array(zRecordingSegment).optional()
});

export const zRecordingList = z.object({
    pageCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    itemCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    items: z.array(zRecording).optional()
});

export const zRtmpConn = z.object({
    id: z.uuid().optional(),
    created: z.string().optional(),
    remoteAddr: z.string().optional(),
    state: zRtmpConnState.optional(),
    path: z.string().optional(),
    query: z.string().optional(),
    user: z.string().optional(),
    inboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundFramesDiscarded: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional()
});

export const zRtmpConnList = z.object({
    pageCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    itemCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    items: z.array(zRtmpConn).optional()
});

export const zRtspConn = z.object({
    id: z.uuid().optional(),
    created: z.string().optional(),
    remoteAddr: z.string().optional(),
    session: z.uuid().nullish(),
    tunnel: z.string().optional(),
    inboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional()
});

export const zRtspConnList = z.object({
    pageCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    itemCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    items: z.array(zRtspConn).optional()
});

export const zRtspSession = z.object({
    id: z.uuid().optional(),
    created: z.string().optional(),
    remoteAddr: z.string().optional(),
    state: zRtspSessionState.optional(),
    path: z.string().optional(),
    query: z.string().optional(),
    user: z.string().optional(),
    transport: z.string().nullish(),
    profile: z.string().nullish(),
    conns: z.array(z.uuid()).optional(),
    inboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    inboundRTPPackets: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    inboundRTPPacketsLost: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    inboundRTPPacketsInError: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    inboundRTPPacketsJitter: z.number().optional(),
    inboundRTCPPackets: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    inboundRTCPPacketsInError: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundRTPPackets: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundRTPPacketsReportedLost: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundRTPPacketsDiscarded: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundRTCPPackets: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtpPacketsReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtpPacketsSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtpPacketsLost: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtpPacketsInError: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtpPacketsJitter: z.number().optional(),
    rtcpPacketsReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtcpPacketsSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtcpPacketsInError: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional()
});

export const zRtspSessionList = z.object({
    pageCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    itemCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    items: z.array(zRtspSession).optional()
});

export const zSrtConn = z.object({
    id: z.uuid().optional(),
    created: z.string().optional(),
    remoteAddr: z.string().optional(),
    state: zSrtConnState.optional(),
    path: z.string().optional(),
    query: z.string().optional(),
    user: z.string().optional(),
    packetsSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedBelated: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsSentUnique: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedUnique: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsSendLoss: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedLoss: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsRetrans: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedRetrans: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsSentACK: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedACK: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsSentNAK: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedNAK: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsSentKM: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedKM: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    usSndDuration: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsSendDrop: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedDrop: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedUndecrypt: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceivedBelated: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSentUnique: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceivedUnique: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceivedLoss: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesRetrans: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceivedRetrans: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSendDrop: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceivedDrop: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceivedUndecrypt: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    usPacketsSendPeriod: z.number().optional(),
    packetsFlowWindow: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsFlightSize: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    msRTT: z.number().optional(),
    mbpsSendRate: z.number().optional(),
    mbpsReceiveRate: z.number().optional(),
    mbpsLinkCapacity: z.number().optional(),
    bytesAvailSendBuf: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesAvailReceiveBuf: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    mbpsMaxBW: z.number().optional(),
    byteMSS: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsSendBuf: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSendBuf: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    msSendBuf: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    msSendTsbPdDelay: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceiveBuf: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceiveBuf: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    msReceiveBuf: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    msReceiveTsbPdDelay: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReorderTolerance: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsReceivedAvgBelatedTime: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    packetsSendLossRate: z.number().optional(),
    packetsReceivedLossRate: z.number().optional(),
    outboundFramesDiscarded: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional()
});

export const zSrtConnList = z.object({
    pageCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    itemCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    items: z.array(zSrtConn).optional()
});

export const zAlwaysAvailableTrack = z.object({
    codec: zAlwaysAvailableTrackCodec.optional(),
    sampleRate: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    channelCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    muLaw: z.boolean().optional()
});

export const zPathConf = z.object({
    name: z.string().optional(),
    source: z.string().optional(),
    sourceFingerprint: z.string().optional(),
    sourceOnDemand: z.boolean().optional(),
    sourceOnDemandStartTimeout: z.string().optional(),
    sourceOnDemandCloseAfter: z.string().optional(),
    maxReaders: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    srtReadPassphrase: z.string().optional(),
    fallback: z.string().nullish(),
    useAbsoluteTimestamp: z.boolean().optional(),
    alwaysAvailable: z.boolean().optional(),
    alwaysAvailableTracks: z.array(zAlwaysAvailableTrack).optional(),
    alwaysAvailableFile: z.string().optional(),
    record: z.boolean().optional(),
    playback: z.boolean().nullish(),
    recordPath: z.string().optional(),
    recordFormat: zRecordFormat.optional(),
    recordPartDuration: z.string().optional(),
    recordMaxPartSize: z.string().optional(),
    recordSegmentDuration: z.string().optional(),
    recordDeleteAfter: z.string().optional(),
    publishUser: z.string().nullish(),
    publishPass: z.string().nullish(),
    publishIPs: z.array(z.string()).nullish(),
    readUser: z.string().nullish(),
    readPass: z.string().nullish(),
    readIPs: z.array(z.string()).nullish(),
    overridePublisher: z.boolean().optional(),
    disablePublisherOverride: z.boolean().nullish(),
    srtPublishPassphrase: z.string().optional(),
    rtspDemuxMpegts: z.boolean().optional(),
    rtspTransport: zRtspTransport.optional(),
    rtspAnyPort: z.boolean().optional(),
    sourceProtocol: zRtspTransport.nullish(),
    sourceAnyPortEnable: z.boolean().nullish(),
    rtspRangeType: zRtspRangeType.optional(),
    rtspRangeStart: z.string().optional(),
    rtspUDPReadBufferSize: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).nullish(),
    rtspUDPSourcePortRange: z.tuple([z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }), z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' })]).optional(),
    mpegtsUDPReadBufferSize: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).nullish(),
    rtpSDP: z.string().optional(),
    rtpUDPReadBufferSize: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).nullish(),
    whepBearerToken: z.string().optional(),
    whepSTUNGatherTimeout: z.string().optional(),
    whepHandshakeTimeout: z.string().optional(),
    whepTrackGatherTimeout: z.string().optional(),
    sourceRedirect: z.string().optional(),
    rpiCameraCamID: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rpiCameraSecondary: z.boolean().optional(),
    rpiCameraWidth: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rpiCameraHeight: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rpiCameraHFlip: z.boolean().optional(),
    rpiCameraVFlip: z.boolean().optional(),
    rpiCameraBrightness: z.number().optional(),
    rpiCameraContrast: z.number().optional(),
    rpiCameraSaturation: z.number().optional(),
    rpiCameraSharpness: z.number().optional(),
    rpiCameraExposure: z.string().optional(),
    rpiCameraAWB: z.string().optional(),
    rpiCameraAWBGains: z.tuple([z.number(), z.number()]).optional(),
    rpiCameraDenoise: z.string().optional(),
    rpiCameraShutter: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rpiCameraMetering: z.string().optional(),
    rpiCameraGain: z.number().optional(),
    rpiCameraEV: z.number().optional(),
    rpiCameraROI: z.string().optional(),
    rpiCameraHDR: z.boolean().optional(),
    rpiCameraTuningFile: z.string().optional(),
    rpiCameraMode: z.string().optional(),
    rpiCameraFPS: z.number().optional(),
    rpiCameraAfMode: z.string().optional(),
    rpiCameraAfRange: z.string().optional(),
    rpiCameraAfSpeed: z.string().optional(),
    rpiCameraLensPosition: z.number().optional(),
    rpiCameraAfWindow: z.string().optional(),
    rpiCameraFlickerPeriod: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rpiCameraTextOverlayEnable: z.boolean().optional(),
    rpiCameraTextOverlay: z.string().optional(),
    rpiCameraCodec: z.string().optional(),
    rpiCameraIDRPeriod: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rpiCameraBitrate: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rpiCameraProfile: z.string().nullish(),
    rpiCameraLevel: z.string().nullish(),
    rpiCameraHardwareH264Profile: z.string().optional(),
    rpiCameraHardwareH264Level: z.string().optional(),
    rpiCameraSoftwareH264Profile: z.string().optional(),
    rpiCameraSoftwareH264Level: z.string().optional(),
    rpiCameraJPEGQuality: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).nullish(),
    rpiCameraMJPEGQuality: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    runOnInit: z.string().optional(),
    runOnInitRestart: z.boolean().optional(),
    runOnDemand: z.string().optional(),
    runOnDemandRestart: z.boolean().optional(),
    runOnDemandStartTimeout: z.string().optional(),
    runOnDemandCloseAfter: z.string().optional(),
    runOnUnDemand: z.string().optional(),
    runOnReady: z.string().optional(),
    runOnReadyRestart: z.boolean().optional(),
    runOnNotReady: z.string().optional(),
    runOnRead: z.string().optional(),
    runOnReadRestart: z.boolean().optional(),
    runOnUnread: z.string().optional(),
    runOnRecordSegmentCreate: z.string().optional(),
    runOnRecordSegmentComplete: z.string().optional()
});

export const zPathConfList = z.object({
    pageCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    itemCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    items: z.array(zPathConf).optional()
});

export const zWebRtciceServer = z.object({
    url: z.string().optional(),
    username: z.string().optional(),
    password: z.string().optional(),
    clientOnly: z.boolean().optional()
});

export const zGlobalConf = z.object({
    logLevel: zLogLevel.optional(),
    logDestinations: z.array(zLogDestination).optional(),
    logStructured: z.boolean().optional(),
    logFile: z.string().optional(),
    sysLogPrefix: z.string().optional(),
    dumpPackets: z.boolean().optional(),
    readTimeout: z.string().optional(),
    writeTimeout: z.string().optional(),
    readBufferCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).nullish(),
    writeQueueSize: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    udpMaxPayloadSize: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    udpReadBufferSize: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    runOnConnect: z.string().optional(),
    runOnConnectRestart: z.boolean().optional(),
    runOnDisconnect: z.string().optional(),
    authMethod: zAuthMethod.optional(),
    authInternalUsers: z.array(zAuthInternalUser).optional(),
    authHTTPAddress: z.string().optional(),
    externalAuthenticationURL: z.string().nullish(),
    authHTTPFingerprint: z.string().optional(),
    authHTTPExclude: z.array(zAuthInternalUserPermission).optional(),
    authJWTJWKS: z.string().optional(),
    authJWTJWKSFingerprint: z.string().optional(),
    authJWTClaimKey: z.string().optional(),
    authJWTIssuer: z.string().optional(),
    authJWTAudience: z.string().optional(),
    authJWTExclude: z.array(zAuthInternalUserPermission).optional(),
    authJWTInHTTPQuery: z.boolean().optional(),
    api: z.boolean().optional(),
    apiAddress: z.string().optional(),
    apiEncryption: z.boolean().optional(),
    apiServerKey: z.string().optional(),
    apiServerCert: z.string().optional(),
    apiAllowOrigin: z.string().nullish(),
    apiAllowOrigins: z.array(z.string()).optional(),
    apiTrustedProxies: z.array(z.string()).optional(),
    metrics: z.boolean().optional(),
    metricsAddress: z.string().optional(),
    metricsEncryption: z.boolean().optional(),
    metricsServerKey: z.string().optional(),
    metricsServerCert: z.string().optional(),
    metricsAllowOrigin: z.string().nullish(),
    metricsAllowOrigins: z.array(z.string()).optional(),
    metricsTrustedProxies: z.array(z.string()).optional(),
    pprof: z.boolean().optional(),
    pprofAddress: z.string().optional(),
    pprofEncryption: z.boolean().optional(),
    pprofServerKey: z.string().optional(),
    pprofServerCert: z.string().optional(),
    pprofAllowOrigin: z.string().nullish(),
    pprofAllowOrigins: z.array(z.string()).optional(),
    pprofTrustedProxies: z.array(z.string()).optional(),
    playback: z.boolean().optional(),
    playbackAddress: z.string().optional(),
    playbackEncryption: z.boolean().optional(),
    playbackServerKey: z.string().optional(),
    playbackServerCert: z.string().optional(),
    playbackAllowOrigin: z.string().nullish(),
    playbackAllowOrigins: z.array(z.string()).optional(),
    playbackTrustedProxies: z.array(z.string()).optional(),
    rtsp: z.boolean().optional(),
    rtspDisable: z.boolean().nullish(),
    protocols: z.array(z.enum([
        'udp',
        'multicast',
        'tcp'
    ])).nullish(),
    rtspTransports: z.array(z.enum([
        'udp',
        'multicast',
        'tcp'
    ])).optional(),
    encryption: zEncryption.nullish(),
    rtspEncryption: zEncryption.optional(),
    rtspAddress: z.string().optional(),
    rtspsAddress: z.string().optional(),
    rtpAddress: z.string().optional(),
    rtcpAddress: z.string().optional(),
    multicastIPRange: z.string().optional(),
    multicastRTPPort: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    multicastRTCPPort: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    srtpAddress: z.string().optional(),
    srtcpAddress: z.string().optional(),
    multicastSRTPPort: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    multicastSRTCPPort: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    rtspServerKey: z.string().optional(),
    rtspServerCert: z.string().optional(),
    authMethods: z.array(zRtspAuthMethod).nullish(),
    rtspAuthMethods: z.array(zRtspAuthMethod).optional(),
    rtspUDPReadBufferSize: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).nullish(),
    rtmp: z.boolean().optional(),
    rtmpDisable: z.boolean().nullish(),
    rtmpEncryption: zEncryption.optional(),
    rtmpAddress: z.string().optional(),
    rtmpsAddress: z.string().optional(),
    rtmpServerKey: z.string().optional(),
    rtmpServerCert: z.string().optional(),
    hls: z.boolean().optional(),
    hlsDisable: z.boolean().nullish(),
    hlsAddress: z.string().optional(),
    hlsEncryption: z.boolean().optional(),
    hlsServerKey: z.string().optional(),
    hlsServerCert: z.string().optional(),
    hlsAllowOrigin: z.string().nullish(),
    hlsAllowOrigins: z.array(z.string()).optional(),
    hlsTrustedProxies: z.array(z.string()).optional(),
    hlsAlwaysRemux: z.boolean().optional(),
    hlsVariant: zHlsVariant.optional(),
    hlsSegmentCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    hlsSegmentDuration: z.string().optional(),
    hlsPartDuration: z.string().optional(),
    hlsSegmentMaxSize: z.string().optional(),
    hlsDirectory: z.string().optional(),
    hlsMuxerCloseAfter: z.string().optional(),
    webrtc: z.boolean().optional(),
    webrtcDisable: z.boolean().nullish(),
    webrtcAddress: z.string().optional(),
    webrtcEncryption: z.boolean().optional(),
    webrtcServerKey: z.string().optional(),
    webrtcServerCert: z.string().optional(),
    webrtcAllowOrigin: z.string().nullish(),
    webrtcAllowOrigins: z.array(z.string()).optional(),
    webrtcTrustedProxies: z.array(z.string()).optional(),
    webrtcLocalUDPAddress: z.string().optional(),
    webrtcLocalTCPAddress: z.string().optional(),
    webrtcIPsFromInterfaces: z.boolean().optional(),
    webrtcIPsFromInterfacesList: z.array(z.string()).optional(),
    webrtcAdditionalHosts: z.array(z.string()).optional(),
    webrtcICEServers2: z.array(zWebRtciceServer).optional(),
    webrtcSTUNGatherTimeout: z.string().optional(),
    webrtcHandshakeTimeout: z.string().optional(),
    webrtcTrackGatherTimeout: z.string().optional(),
    webrtcICEUDPMuxAddress: z.string().nullish(),
    webrtcICETCPMuxAddress: z.string().nullish(),
    webrtcICEHostNAT1To1IPs: z.array(z.string()).nullish(),
    webrtcICEServers: z.array(z.string()).nullish(),
    srt: z.boolean().optional(),
    srtAddress: z.string().optional(),
    record: z.boolean().nullish(),
    recordPath: z.string().nullish(),
    recordFormat: zRecordFormat.nullish(),
    recordPartDuration: z.string().nullish(),
    recordSegmentDuration: z.string().nullish(),
    recordDeleteAfter: z.string().nullish()
});

export const zWebRtcSession = z.object({
    id: z.uuid().optional(),
    created: z.string().optional(),
    remoteAddr: z.string().optional(),
    peerConnectionEstablished: z.boolean().optional(),
    localCandidate: z.string().optional(),
    remoteCandidate: z.string().optional(),
    state: zWebRtcSessionState.optional(),
    path: z.string().optional(),
    query: z.string().optional(),
    user: z.string().optional(),
    inboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    inboundRTPPackets: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    inboundRTPPacketsLost: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    inboundRTPPacketsJitter: z.number().optional(),
    inboundRTCPPackets: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundBytes: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundRTPPackets: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundRTCPPackets: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    outboundFramesDiscarded: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    bytesSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtpPacketsReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtpPacketsSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtpPacketsLost: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtpPacketsJitter: z.number().optional(),
    rtcpPacketsReceived: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional(),
    rtcpPacketsSent: z.coerce.bigint().min(BigInt('0'), { error: 'Invalid value: Expected uint64 to be >= 0' }).max(BigInt('18446744073709551615'), { error: 'Invalid value: Expected uint64 to be <= 18446744073709551615' }).optional()
});

export const zWebRtcSessionList = z.object({
    pageCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    itemCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    items: z.array(zWebRtcSession).optional()
});

export const zInfoData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zInfoResponse = zInfo;

export const zAuthJwksRefreshData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zAuthJwksRefreshResponse = zOk;

export const zConfigGlobalGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zConfigGlobalGetResponse = zGlobalConf;

export const zConfigGlobalSetData = z.object({
    body: zGlobalConf,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zConfigGlobalSetResponse = zOk;

export const zConfigPathDefaultsGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zConfigPathDefaultsGetResponse = zPathConf;

export const zConfigPathDefaultsPatchData = z.object({
    body: zPathConf,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zConfigPathDefaultsPatchResponse = zOk;

export const zConfigPathsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zConfigPathsListResponse = zPathConfList;

export const zConfigPathsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        name: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zConfigPathsGetResponse = zPathConf;

export const zConfigPathsAddData = z.object({
    body: zPathConf,
    path: z.object({
        name: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zConfigPathsAddResponse = zOk;

export const zConfigPathsPatchData = z.object({
    body: zPathConf,
    path: z.object({
        name: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zConfigPathsPatchResponse = zOk;

export const zConfigPathsReplaceData = z.object({
    body: zPathConf,
    path: z.object({
        name: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zConfigPathsReplaceResponse = zOk;

export const zConfigPathsDeleteData = z.object({
    body: z.never().optional(),
    path: z.object({
        name: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zConfigPathsDeleteResponse = zOk;

export const zHlsMuxersListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zHlsMuxersListResponse = zHlsMuxerList;

export const zHlsMuxersGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        name: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zHlsMuxersGetResponse = zHlsMuxer;

export const zPathsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zPathsListResponse = zPathList;

export const zPathsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        name: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zPathsGetResponse = zPath;

export const zRtspConnsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zRtspConnsListResponse = zRtspConnList;

export const zRtspConnsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtspConnsGetResponse = zRtspConn;

export const zRtspSessionsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zRtspSessionsListResponse = zRtspSessionList;

export const zRtspSessionsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtspSessionsGetResponse = zRtspSession;

export const zRtspSessionsKickData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtspSessionsKickResponse = zOk;

export const zRtspsConnsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zRtspsConnsListResponse = zRtspConnList;

export const zRtspsConnsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtspsConnsGetResponse = zRtspConn;

export const zRtspsSessionsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zRtspsSessionsListResponse = zRtspSessionList;

export const zRtspsSessionsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtspsSessionsGetResponse = zRtspSession;

export const zRtspsSessionsKickData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtspsSessionsKickResponse = zOk;

export const zRtmpConnsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zRtmpConnsListResponse = zRtmpConnList;

export const zRtmpConnectionsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtmpConnectionsGetResponse = zRtmpConn;

export const zRtmpConnsKickData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtmpConnsKickResponse = zOk;

export const zRtmpsConnsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zRtmpsConnsListResponse = zRtmpConnList;

export const zRtmpsConnectionsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtmpsConnectionsGetResponse = zRtmpConn;

export const zRtmpsConnsKickData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRtmpsConnsKickResponse = zOk;

export const zSrtConnsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zSrtConnsListResponse = zSrtConnList;

export const zSrtConnsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zSrtConnsGetResponse = zSrtConn;

export const zSrtConnsKickData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zSrtConnsKickResponse = zOk;

export const zWebrtcSessionsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zWebrtcSessionsListResponse = zWebRtcSessionList;

export const zWebrtcSessionsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zWebrtcSessionsGetResponse = zWebRtcSession;

export const zWebrtcSessionsKickData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zWebrtcSessionsKickResponse = zOk;

export const zRecordingsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.int().optional().default(0),
        itemsPerPage: z.int().optional().default(100)
    }).optional()
});

/**
 * the request was successful.
 */
export const zRecordingsListResponse = zRecordingList;

export const zRecordingsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        name: z.string()
    }),
    query: z.never().optional()
});

/**
 * the request was successful.
 */
export const zRecordingsGetResponse = zRecording;

export const zRecordingsDeleteSegmentData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        path: z.string(),
        start: z.string()
    })
});

/**
 * the request was successful.
 */
export const zRecordingsDeleteSegmentResponse = zOk;
